replicaCount: 1

image:
  repository: anujjain07/cicd-demo
  tag: "latest"
  pullPolicy: IfNotPresent

app:
  port: 8080
  version: "1.0.0"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 40
  periodSeconds: 5
